/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.github.hasat.frame;

import io.github.hasat.card.Card;
import io.github.hasat.card.CardType;
import io.github.hasat.database.MySQL;
import io.github.hasat.user.User;
import io.github.hasat.user.UserManager;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.swing.Timer;

/**
 *
 * @author hakan
 */
public class AddCardFrame extends javax.swing.JFrame {
    
    private String randomCardID;

    /**
     * Creates new form RegisterFrame
     */
    public AddCardFrame() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        Random random = new Random();
        
        randomCardID = (10000000000L + ((long) random.nextInt(900000000) * 100) + random.nextInt(100)) + "";
        
        randomCardID = new StringBuilder(randomCardID).insert(5, "-").insert(11, "-").toString();
        
        cardNumberText.setText(randomCardID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        secondNewMailLabel = new javax.swing.JLabel();
        cardNumberText = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        backButton = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        changeMailButton = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        cardNumberLabel = new javax.swing.JLabel();
        newMailLabel = new javax.swing.JLabel();
        cardNameText = new javax.swing.JTextField();
        cardTypes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HASAT Ulaşım");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/bus.png")).getImage());
        setResizable(false);

        panel.setBackground(new java.awt.Color(2, 44, 74));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/newbus.png"))); // NOI18N
        logoLabel.setText("HASAT Ulaşım");
        logoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        secondNewMailLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        secondNewMailLabel.setForeground(new java.awt.Color(255, 255, 255));
        secondNewMailLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/card.png"))); // NOI18N
        secondNewMailLabel.setText("Kart Tipi:");
        panel.add(secondNewMailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        cardNumberText.setEditable(false);
        cardNumberText.setBackground(new java.awt.Color(2, 44, 74));
        cardNumberText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        cardNumberText.setForeground(new java.awt.Color(255, 255, 255));
        cardNumberText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        panel.add(cardNumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 430, 38));
        panel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 430, 11));
        panel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 430, 10));

        backButton.setBackground(new java.awt.Color(2, 44, 74));
        backButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/back.png"))); // NOI18N
        backButton.setText("Geri Dön");
        backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        backButton.setFocusPainted(false);
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backButtonMouseEntered(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        panel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 200, 80));

        warningLabel.setBackground(new java.awt.Color(2, 44, 74));
        warningLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(255, 255, 255));
        warningLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        warningLabel.setOpaque(true);
        panel.add(warningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 196, 200, 170));

        changeMailButton.setBackground(new java.awt.Color(2, 44, 74));
        changeMailButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        changeMailButton.setForeground(new java.awt.Color(255, 255, 255));
        changeMailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/add.png"))); // NOI18N
        changeMailButton.setText("Kart Ekle");
        changeMailButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        changeMailButton.setFocusPainted(false);
        changeMailButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeMailButtonMouseEntered(evt);
            }
        });
        changeMailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeMailButtonActionPerformed(evt);
            }
        });
        panel.add(changeMailButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 430, 80));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 10, 470));

        cardNumberLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cardNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardNumberLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/number.png"))); // NOI18N
        cardNumberLabel.setText("Kart Numarası (xxxxx-xxxxx-x):");
        panel.add(cardNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        newMailLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        newMailLabel.setForeground(new java.awt.Color(255, 255, 255));
        newMailLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/text.png"))); // NOI18N
        newMailLabel.setText("Kart Adı:");
        panel.add(newMailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        cardNameText.setBackground(new java.awt.Color(2, 44, 74));
        cardNameText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        cardNameText.setForeground(new java.awt.Color(255, 255, 255));
        cardNameText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        cardNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cardNameTextKeyTyped(evt);
            }
        });
        panel.add(cardNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 430, 38));

        cardTypes.setBackground(new java.awt.Color(2, 44, 74));
        cardTypes.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        cardTypes.setForeground(new java.awt.Color(255, 255, 255));
        cardTypes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NORMAL", "OGRENCI", "ENGELLI" }));
        cardTypes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panel.add(cardTypes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 430, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        
        new ProfileFrame().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void changeMailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeMailButtonActionPerformed
        String cardNumber = cardNumberText.getText();
        String cardName = cardNameText.getText();
        
        if (cardName.isEmpty()) {
            cardNameText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Kart adı kısmını<br>&nbsp;doldurmalısınız!</html>");
            return;
        }
        
        if (cardName.length() < 4) {
            cardNameText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Kart bir Kart<br>&nbsp;adı girmelisiniz!</html>");
            return;
        }
       
        User user = UserManager.getUser();
        
        if (user == null) {
            dispose();
            
            new LoginFrame().setVisible(true);
            
            return;
        }
        
        List<Card> cards = user.getCards();
        
        if (cards.size() == 3) {
            cardNameText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Kart limitine<br>&nbsp;ulaşmışsınız! (3/3)</html>");
            return;
        }
       
        warningLabel.setBackground(new Color(1,95,24));
        warningLabel.setText("<html>&nbsp;● Kartınız başarıyla<br>&nbsp;eklendi!<br><br>&nbsp;Yönlendiriliyorsunuz...</html>");
        
        CardType cardType;
        
        String cardTypeName = cardTypes.getItemAt(cardTypes.getSelectedIndex());
        
        switch (cardTypeName) {
            case "OGRENCI":
                cardType = CardType.STUDENT;
                break;
            case "ENGELLI":
                cardType = CardType.MALFORMED;
                break;
            default:
                cardType = CardType.NORMAL;
                break;
        }
        
        
        String time = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(new Date(System.currentTimeMillis()));
        
        Card card = new Card(user.getID(), cardNumber, cardName, 0, time, cardType);
        
        MySQL.createCard(card);
        
        user.getCards().add(card);
        
        ActionListener action = (ActionEvent ae) -> {
            dispose();

            new CardsFrame().setVisible(true);
        };

        Timer t = new Timer(3000, action);

        t.setRepeats(false);
        t.start();
    }//GEN-LAST:event_changeMailButtonActionPerformed

    private void backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseEntered
        backButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_backButtonMouseEntered

    private void changeMailButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeMailButtonMouseEntered
        changeMailButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_changeMailButtonMouseEntered

    private void cardNameTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNameTextKeyTyped
        if (cardNameText.getText().length() > 10) {
            evt.consume();
            return;
        }
                
        cardNameText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_cardNameTextKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField cardNameText;
    private javax.swing.JLabel cardNumberLabel;
    private javax.swing.JTextField cardNumberText;
    private javax.swing.JComboBox<String> cardTypes;
    private javax.swing.JButton changeMailButton;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel newMailLabel;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel secondNewMailLabel;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
