/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package io.github.hasat.frame;

import java.awt.Cursor;

/**
 *
 * @author hakan
 */
public class BusTimesFrame extends javax.swing.JFrame {

    /** Creates new form ProfilePage */
    public BusTimesFrame() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        myProfileButton = new javax.swing.JButton();
        exitButton2 = new javax.swing.JButton();
        busTimesButton = new javax.swing.JButton();
        myCardsButton = new javax.swing.JButton();
        cardSettingsButton = new javax.swing.JButton();
        cardOneIDLabel = new javax.swing.JLabel();
        cardOneIDLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        addCardButton = new javax.swing.JButton();
        removeCardButton = new javax.swing.JButton();
        updateBalanceButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HASAT Ulaşım");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/bus.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(2, 44, 74));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 20)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/bus16px.png"))); // NOI18N
        logoLabel.setText("  HASAT Ulaşım");
        logoLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        logoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        logoLabel.setIconTextGap(1);
        logoLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 70));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 10, 530));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 540, 10));

        myProfileButton.setBackground(new java.awt.Color(2, 44, 74));
        myProfileButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        myProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        myProfileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/name.png"))); // NOI18N
        myProfileButton.setText("Profilim");
        myProfileButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        myProfileButton.setFocusPainted(false);
        myProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myProfileButtonMouseEntered(evt);
            }
        });
        myProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myProfileButtonActionPerformed(evt);
            }
        });
        jPanel1.add(myProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 210, 40));

        exitButton2.setBackground(new java.awt.Color(2, 44, 74));
        exitButton2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        exitButton2.setForeground(new java.awt.Color(250, 49, 74));
        exitButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/logout.png"))); // NOI18N
        exitButton2.setText("Çıkış Yap");
        exitButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 49, 74), 1, true));
        exitButton2.setFocusPainted(false);
        exitButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButton2MouseEntered(evt);
            }
        });
        exitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 210, 40));

        busTimesButton.setBackground(new java.awt.Color(2, 44, 74));
        busTimesButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        busTimesButton.setForeground(new java.awt.Color(255, 255, 255));
        busTimesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/clock.png"))); // NOI18N
        busTimesButton.setText("Otobüs Saatleri");
        busTimesButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        busTimesButton.setFocusPainted(false);
        busTimesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                busTimesButtonMouseEntered(evt);
            }
        });
        jPanel1.add(busTimesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 210, 40));

        myCardsButton.setBackground(new java.awt.Color(2, 44, 74));
        myCardsButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        myCardsButton.setForeground(new java.awt.Color(255, 255, 255));
        myCardsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/card.png"))); // NOI18N
        myCardsButton.setText("Kartlarım");
        myCardsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        myCardsButton.setFocusPainted(false);
        myCardsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myCardsButtonMouseEntered(evt);
            }
        });
        myCardsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myCardsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(myCardsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 210, 40));

        cardSettingsButton.setBackground(new java.awt.Color(2, 44, 74));
        cardSettingsButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cardSettingsButton.setForeground(new java.awt.Color(255, 255, 255));
        cardSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/settings.png"))); // NOI18N
        cardSettingsButton.setText("Kart Ayarları");
        cardSettingsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        cardSettingsButton.setFocusPainted(false);
        cardSettingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cardSettingsButtonMouseEntered(evt);
            }
        });
        cardSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardSettingsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cardSettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 210, 40));

        cardOneIDLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 30)); // NOI18N
        cardOneIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardOneIDLabel.setText("Maalesef daha belediye ile anlaşamadık...");
        jPanel1.add(cardOneIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 540, 90));

        cardOneIDLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 48)); // NOI18N
        cardOneIDLabel1.setForeground(new java.awt.Color(255, 255, 255));
        cardOneIDLabel1.setText("Çok yakında!");
        jPanel1.add(cardOneIDLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 540, 90));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 210, 10));

        addCardButton.setBackground(new java.awt.Color(2, 44, 74));
        addCardButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        addCardButton.setForeground(new java.awt.Color(255, 255, 255));
        addCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/add.png"))); // NOI18N
        addCardButton.setText("Kart Ekle");
        addCardButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        addCardButton.setFocusPainted(false);
        addCardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addCardButtonMouseEntered(evt);
            }
        });
        addCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCardButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addCardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 210, 40));

        removeCardButton.setBackground(new java.awt.Color(2, 44, 74));
        removeCardButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        removeCardButton.setForeground(new java.awt.Color(255, 255, 255));
        removeCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/remove.png"))); // NOI18N
        removeCardButton.setText("Kart Sil");
        removeCardButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        removeCardButton.setFocusPainted(false);
        removeCardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeCardButtonMouseEntered(evt);
            }
        });
        removeCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCardButtonActionPerformed(evt);
            }
        });
        jPanel1.add(removeCardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 210, 40));

        updateBalanceButton2.setBackground(new java.awt.Color(2, 44, 74));
        updateBalanceButton2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        updateBalanceButton2.setForeground(new java.awt.Color(255, 255, 255));
        updateBalanceButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/money.png"))); // NOI18N
        updateBalanceButton2.setText("Bakiye Yükle");
        updateBalanceButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        updateBalanceButton2.setFocusPainted(false);
        updateBalanceButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBalanceButton2MouseEntered(evt);
            }
        });
        updateBalanceButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBalanceButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(updateBalanceButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myProfileButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myProfileButtonMouseEntered
        myProfileButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_myProfileButtonMouseEntered

    private void myProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myProfileButtonActionPerformed
        dispose();
        
        new ProfileFrame().setVisible(true);
    }//GEN-LAST:event_myProfileButtonActionPerformed

    private void exitButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButton2MouseEntered
        exitButton2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_exitButton2MouseEntered

    private void exitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_exitButton2ActionPerformed

    private void busTimesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busTimesButtonMouseEntered
        busTimesButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_busTimesButtonMouseEntered

    private void myCardsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myCardsButtonMouseEntered
       myCardsButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_myCardsButtonMouseEntered

    private void cardSettingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardSettingsButtonMouseEntered
        cardSettingsButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_cardSettingsButtonMouseEntered

    private void addCardButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCardButtonMouseEntered
        addCardButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_addCardButtonMouseEntered

    private void removeCardButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCardButtonMouseEntered
        removeCardButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_removeCardButtonMouseEntered

    private void addCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCardButtonActionPerformed
        dispose();
        
        new AddCardFrame().setVisible(true);
    }//GEN-LAST:event_addCardButtonActionPerformed

    private void myCardsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myCardsButtonActionPerformed
        dispose();
        
        new CardsFrame().setVisible(true);
    }//GEN-LAST:event_myCardsButtonActionPerformed

    private void removeCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCardButtonActionPerformed
        dispose();
        
        new RemoveCardFrame().setVisible(true);
    }//GEN-LAST:event_removeCardButtonActionPerformed

    private void cardSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardSettingsButtonActionPerformed
        dispose();
        
        new CardSettingsFrame().setVisible(true);
    }//GEN-LAST:event_cardSettingsButtonActionPerformed

    private void updateBalanceButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBalanceButton2MouseEntered
        updateBalanceButton2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_updateBalanceButton2MouseEntered

    private void updateBalanceButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBalanceButton2ActionPerformed
        dispose();

        new BalanceCardFrame().setVisible(true);
    }//GEN-LAST:event_updateBalanceButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCardButton;
    private javax.swing.JButton busTimesButton;
    private javax.swing.JLabel cardOneIDLabel;
    private javax.swing.JLabel cardOneIDLabel1;
    private javax.swing.JButton cardSettingsButton;
    private javax.swing.JButton exitButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton myCardsButton;
    private javax.swing.JButton myProfileButton;
    private javax.swing.JButton removeCardButton;
    private javax.swing.JButton updateBalanceButton2;
    // End of variables declaration//GEN-END:variables

}
