/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package io.github.hasat.frame;

import io.github.hasat.card.Card;
import io.github.hasat.user.User;
import io.github.hasat.user.UserManager;
import java.awt.Cursor;
import java.util.List;

/**
 *
 * @author hakan
 */
public class CardsFrame extends javax.swing.JFrame {

    /** Creates new form ProfilePage */
    public CardsFrame() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        cardOnePane.setVisible(false);
        cardTwoPane.setVisible(false);
        cardThreePane.setVisible(false);
        
        User user = UserManager.getUser();
        
        if (user == null) {
            dispose();
            
            new LoginFrame().setVisible(true);
            
            return;
        }
        
        List<Card> cards = user.getCards();
        
        if (cards.isEmpty()) return;
                        
        try {
            cardOnePane.setVisible(true);
            
            Card cardOne = cards.get(0);
            
            cardOneIDText.setText(cardOne.getCardID());
            cardOneNameText.setText(cardOne.getCardName());
            cardOneBalanceText.setText(cardOne.getBalance() + " Türk Lirası");
            cardOneType.setText(cardOne.getCardType().getName());

            cardOneSlot = cardOne;
        } catch (IndexOutOfBoundsException e) {
            
        }
        
        try {
            Card cardTwo = cards.get(1);
            
            cardTwoPane.setVisible(true);
            
            cardTwoIDText.setText(cardTwo.getCardID());
            cardTwoNameText.setText(cardTwo.getCardName());
            cardTwoBalanceText.setText(cardTwo.getBalance() + " Türk Lirası");
            cardTwoType.setText(cardTwo.getCardType().getName());

            cardTwoSlot = cardTwo;
        } catch (IndexOutOfBoundsException e) {
           
        }
        
        try {
            Card cardThree = cards.get(2);
            
            cardThreePane.setVisible(true);
                        
            cardThreeIDText.setText(cardThree.getCardID());
            cardThreeNameText.setText(cardThree.getCardName());
            cardThreeBalanceText.setText(cardThree.getBalance() + " Türk Lirası");
            cardThreeType.setText(cardThree.getCardType().getName());

            cardThreeSlot = cardThree;
        } catch (IndexOutOfBoundsException e) {
           
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        myProfileButton = new javax.swing.JButton();
        exitButton2 = new javax.swing.JButton();
        busTimesButton = new javax.swing.JButton();
        myCardsButton = new javax.swing.JButton();
        addCardButton = new javax.swing.JButton();
        cardThreePane = new javax.swing.JLayeredPane();
        cardThreeIDLabel = new javax.swing.JLabel();
        cardThreeNameLabel = new javax.swing.JLabel();
        cardThreeBalanceLabel = new javax.swing.JLabel();
        cardThreeNameText = new javax.swing.JLabel();
        cardThreeBalanceText = new javax.swing.JLabel();
        cardThreeIcon = new javax.swing.JLabel();
        cardThreeIDText = new javax.swing.JLabel();
        cardThreeType = new javax.swing.JLabel();
        cardTwoPane = new javax.swing.JLayeredPane();
        cardTwoIDLabel = new javax.swing.JLabel();
        cardTwoNameLabel = new javax.swing.JLabel();
        cardTwoBalanceLabel = new javax.swing.JLabel();
        cardTwoNameText = new javax.swing.JLabel();
        cardTwoBalanceText = new javax.swing.JLabel();
        cardTwoIcon = new javax.swing.JLabel();
        cardTwoIDText = new javax.swing.JLabel();
        cardTwoType = new javax.swing.JLabel();
        cardOnePane = new javax.swing.JLayeredPane();
        cardOneIDLabel = new javax.swing.JLabel();
        cardOneNameLabel = new javax.swing.JLabel();
        cardOneBalanceLabel = new javax.swing.JLabel();
        cardOneNameText = new javax.swing.JLabel();
        cardOneBalanceText = new javax.swing.JLabel();
        cardOneIcon = new javax.swing.JLabel();
        cardOneIDText = new javax.swing.JLabel();
        cardOneType = new javax.swing.JLabel();
        removeCardButton = new javax.swing.JButton();
        cardSettingsButton = new javax.swing.JButton();
        updateBalanceButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HASAT Ulaşım");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/bus.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(2, 44, 74));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 20)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/bus16px.png"))); // NOI18N
        logoLabel.setText("  HASAT Ulaşım");
        logoLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        logoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        logoLabel.setIconTextGap(1);
        logoLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 70));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 10, 520));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 210, 10));

        myProfileButton.setBackground(new java.awt.Color(2, 44, 74));
        myProfileButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        myProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        myProfileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/name.png"))); // NOI18N
        myProfileButton.setText("Profilim");
        myProfileButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        myProfileButton.setFocusPainted(false);
        myProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myProfileButtonMouseEntered(evt);
            }
        });
        myProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myProfileButtonActionPerformed(evt);
            }
        });
        jPanel1.add(myProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 210, 40));

        exitButton2.setBackground(new java.awt.Color(2, 44, 74));
        exitButton2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        exitButton2.setForeground(new java.awt.Color(250, 49, 74));
        exitButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/logout.png"))); // NOI18N
        exitButton2.setText("Çıkış Yap");
        exitButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 49, 74), 1, true));
        exitButton2.setFocusPainted(false);
        exitButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButton2MouseEntered(evt);
            }
        });
        exitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 210, 40));

        busTimesButton.setBackground(new java.awt.Color(2, 44, 74));
        busTimesButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        busTimesButton.setForeground(new java.awt.Color(255, 255, 255));
        busTimesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/clock.png"))); // NOI18N
        busTimesButton.setText("Otobüs Saatleri");
        busTimesButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        busTimesButton.setFocusPainted(false);
        busTimesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                busTimesButtonMouseEntered(evt);
            }
        });
        busTimesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busTimesButtonActionPerformed(evt);
            }
        });
        jPanel1.add(busTimesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 210, 40));

        myCardsButton.setBackground(new java.awt.Color(2, 44, 74));
        myCardsButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        myCardsButton.setForeground(new java.awt.Color(255, 255, 255));
        myCardsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/card.png"))); // NOI18N
        myCardsButton.setText("Kartlarım");
        myCardsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        myCardsButton.setFocusPainted(false);
        myCardsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myCardsButtonMouseEntered(evt);
            }
        });
        jPanel1.add(myCardsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 210, 40));

        addCardButton.setBackground(new java.awt.Color(2, 44, 74));
        addCardButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        addCardButton.setForeground(new java.awt.Color(255, 255, 255));
        addCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/add.png"))); // NOI18N
        addCardButton.setText("Kart Ekle");
        addCardButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        addCardButton.setFocusPainted(false);
        addCardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addCardButtonMouseEntered(evt);
            }
        });
        addCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCardButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addCardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 210, 40));

        cardThreePane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        cardThreePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardThreeIDLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        cardThreeIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardThreeIDLabel.setText("Kart Numarası:");
        cardThreePane.add(cardThreeIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        cardThreeNameLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        cardThreeNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardThreeNameLabel.setText("Kart Adı:");
        cardThreePane.add(cardThreeNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 40));

        cardThreeBalanceLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        cardThreeBalanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardThreeBalanceLabel.setText("Bakiye:");
        cardThreePane.add(cardThreeBalanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 60, 40));

        cardThreeNameText.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cardThreeNameText.setForeground(new java.awt.Color(255, 255, 255));
        cardThreeNameText.setText("<cardName>");
        cardThreePane.add(cardThreeNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 250, 40));

        cardThreeBalanceText.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cardThreeBalanceText.setForeground(new java.awt.Color(255, 255, 255));
        cardThreeBalanceText.setText("<cardBalance>");
        cardThreePane.add(cardThreeBalanceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 250, 40));

        cardThreeIcon.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cardThreeIcon.setForeground(new java.awt.Color(255, 255, 255));
        cardThreeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/cardbig.png"))); // NOI18N
        cardThreeIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cardThreeIcon.setVerifyInputWhenFocusTarget(false);
        cardThreeIcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cardThreePane.add(cardThreeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 100, 70));

        cardThreeIDText.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cardThreeIDText.setForeground(new java.awt.Color(255, 255, 255));
        cardThreeIDText.setText("<cardID>");
        cardThreePane.add(cardThreeIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 250, 40));

        cardThreeType.setFont(new java.awt.Font("Segoe UI Semilight", 1, 17)); // NOI18N
        cardThreeType.setForeground(new java.awt.Color(255, 255, 255));
        cardThreeType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardThreeType.setText("<type>");
        cardThreePane.add(cardThreeType, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 110, 40));

        jPanel1.add(cardThreePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 560, 140));

        cardTwoPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        cardTwoPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardTwoIDLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        cardTwoIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardTwoIDLabel.setText("Kart Numarası:");
        cardTwoPane.add(cardTwoIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        cardTwoNameLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        cardTwoNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardTwoNameLabel.setText("Kart Adı:");
        cardTwoPane.add(cardTwoNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 40));

        cardTwoBalanceLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        cardTwoBalanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardTwoBalanceLabel.setText("Bakiye:");
        cardTwoPane.add(cardTwoBalanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 60, 40));

        cardTwoNameText.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cardTwoNameText.setForeground(new java.awt.Color(255, 255, 255));
        cardTwoNameText.setText("<cardName>");
        cardTwoPane.add(cardTwoNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 250, 40));

        cardTwoBalanceText.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cardTwoBalanceText.setForeground(new java.awt.Color(255, 255, 255));
        cardTwoBalanceText.setText("<cardBalance>");
        cardTwoPane.add(cardTwoBalanceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 250, 40));

        cardTwoIcon.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cardTwoIcon.setForeground(new java.awt.Color(255, 255, 255));
        cardTwoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/cardbig.png"))); // NOI18N
        cardTwoIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cardTwoIcon.setVerifyInputWhenFocusTarget(false);
        cardTwoIcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cardTwoPane.add(cardTwoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 100, 70));

        cardTwoIDText.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cardTwoIDText.setForeground(new java.awt.Color(255, 255, 255));
        cardTwoIDText.setText("<cardID>");
        cardTwoPane.add(cardTwoIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 250, 40));

        cardTwoType.setFont(new java.awt.Font("Segoe UI Semilight", 1, 17)); // NOI18N
        cardTwoType.setForeground(new java.awt.Color(255, 255, 255));
        cardTwoType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardTwoType.setText("<type>");
        cardTwoPane.add(cardTwoType, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 110, 40));

        jPanel1.add(cardTwoPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 560, 140));

        cardOnePane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        cardOnePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardOneIDLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        cardOneIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardOneIDLabel.setText("Kart Numarası:");
        cardOnePane.add(cardOneIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        cardOneNameLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        cardOneNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardOneNameLabel.setText("Kart Adı:");
        cardOnePane.add(cardOneNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 40));

        cardOneBalanceLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        cardOneBalanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        cardOneBalanceLabel.setText("Bakiye:");
        cardOnePane.add(cardOneBalanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 60, 40));

        cardOneNameText.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cardOneNameText.setForeground(new java.awt.Color(255, 255, 255));
        cardOneNameText.setText("<cardName>");
        cardOnePane.add(cardOneNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 250, 40));

        cardOneBalanceText.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cardOneBalanceText.setForeground(new java.awt.Color(255, 255, 255));
        cardOneBalanceText.setText("<cardBalance>");
        cardOnePane.add(cardOneBalanceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 250, 40));

        cardOneIcon.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cardOneIcon.setForeground(new java.awt.Color(255, 255, 255));
        cardOneIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/cardbig.png"))); // NOI18N
        cardOneIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cardOneIcon.setVerifyInputWhenFocusTarget(false);
        cardOneIcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cardOnePane.add(cardOneIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 100, 70));

        cardOneIDText.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cardOneIDText.setForeground(new java.awt.Color(255, 255, 255));
        cardOneIDText.setText("<cardID>");
        cardOnePane.add(cardOneIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 250, 40));

        cardOneType.setFont(new java.awt.Font("Segoe UI Semilight", 1, 17)); // NOI18N
        cardOneType.setForeground(new java.awt.Color(255, 255, 255));
        cardOneType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardOneType.setText("<type>");
        cardOnePane.add(cardOneType, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 110, 40));

        jPanel1.add(cardOnePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 560, 140));

        removeCardButton.setBackground(new java.awt.Color(2, 44, 74));
        removeCardButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        removeCardButton.setForeground(new java.awt.Color(255, 255, 255));
        removeCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/remove.png"))); // NOI18N
        removeCardButton.setText("Kart Sil");
        removeCardButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        removeCardButton.setFocusPainted(false);
        removeCardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeCardButtonMouseEntered(evt);
            }
        });
        removeCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCardButtonActionPerformed(evt);
            }
        });
        jPanel1.add(removeCardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 210, 40));

        cardSettingsButton.setBackground(new java.awt.Color(2, 44, 74));
        cardSettingsButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cardSettingsButton.setForeground(new java.awt.Color(255, 255, 255));
        cardSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/settings.png"))); // NOI18N
        cardSettingsButton.setText("Kart Ayarları");
        cardSettingsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        cardSettingsButton.setFocusPainted(false);
        cardSettingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cardSettingsButtonMouseEntered(evt);
            }
        });
        cardSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardSettingsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cardSettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 210, 40));

        updateBalanceButton.setBackground(new java.awt.Color(2, 44, 74));
        updateBalanceButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        updateBalanceButton.setForeground(new java.awt.Color(255, 255, 255));
        updateBalanceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/money.png"))); // NOI18N
        updateBalanceButton.setText("Bakiye Yükle");
        updateBalanceButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        updateBalanceButton.setFocusPainted(false);
        updateBalanceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBalanceButtonMouseEntered(evt);
            }
        });
        updateBalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBalanceButtonActionPerformed(evt);
            }
        });
        jPanel1.add(updateBalanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myProfileButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myProfileButtonMouseEntered
        myProfileButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_myProfileButtonMouseEntered

    private void myProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myProfileButtonActionPerformed
        dispose();
        
        new ProfileFrame().setVisible(true);
    }//GEN-LAST:event_myProfileButtonActionPerformed

    private void exitButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButton2MouseEntered
        exitButton2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_exitButton2MouseEntered

    private void exitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_exitButton2ActionPerformed

    private void busTimesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busTimesButtonMouseEntered
        busTimesButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_busTimesButtonMouseEntered

    private void myCardsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myCardsButtonMouseEntered
        myCardsButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_myCardsButtonMouseEntered

    private void addCardButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCardButtonMouseEntered
        addCardButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_addCardButtonMouseEntered

    private void busTimesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busTimesButtonActionPerformed
        dispose();
        
        new BusTimesFrame().setVisible(true);
    }//GEN-LAST:event_busTimesButtonActionPerformed

    private void addCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCardButtonActionPerformed
        dispose();
        
        new AddCardFrame().setVisible(true);
    }//GEN-LAST:event_addCardButtonActionPerformed

    private void removeCardButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCardButtonMouseEntered
        removeCardButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_removeCardButtonMouseEntered

    private void removeCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCardButtonActionPerformed
        dispose();

        new RemoveCardFrame().setVisible(true);
    }//GEN-LAST:event_removeCardButtonActionPerformed

    private void cardSettingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardSettingsButtonMouseEntered
        cardSettingsButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_cardSettingsButtonMouseEntered

    private void cardSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardSettingsButtonActionPerformed
        dispose();

        new CardSettingsFrame().setVisible(true);
    }//GEN-LAST:event_cardSettingsButtonActionPerformed

    private void updateBalanceButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBalanceButtonMouseEntered
        updateBalanceButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_updateBalanceButtonMouseEntered

    private void updateBalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBalanceButtonActionPerformed
        dispose();

        new BalanceCardFrame().setVisible(true);
    }//GEN-LAST:event_updateBalanceButtonActionPerformed

    
    private Card cardOneSlot, cardTwoSlot, cardThreeSlot;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCardButton;
    private javax.swing.JButton busTimesButton;
    private javax.swing.JLabel cardOneBalanceLabel;
    private javax.swing.JLabel cardOneBalanceText;
    private javax.swing.JLabel cardOneIDLabel;
    private javax.swing.JLabel cardOneIDText;
    private javax.swing.JLabel cardOneIcon;
    private javax.swing.JLabel cardOneNameLabel;
    private javax.swing.JLabel cardOneNameText;
    private javax.swing.JLayeredPane cardOnePane;
    private javax.swing.JLabel cardOneType;
    private javax.swing.JButton cardSettingsButton;
    private javax.swing.JLabel cardThreeBalanceLabel;
    private javax.swing.JLabel cardThreeBalanceText;
    private javax.swing.JLabel cardThreeIDLabel;
    private javax.swing.JLabel cardThreeIDText;
    private javax.swing.JLabel cardThreeIcon;
    private javax.swing.JLabel cardThreeNameLabel;
    private javax.swing.JLabel cardThreeNameText;
    private javax.swing.JLayeredPane cardThreePane;
    private javax.swing.JLabel cardThreeType;
    private javax.swing.JLabel cardTwoBalanceLabel;
    private javax.swing.JLabel cardTwoBalanceText;
    private javax.swing.JLabel cardTwoIDLabel;
    private javax.swing.JLabel cardTwoIDText;
    private javax.swing.JLabel cardTwoIcon;
    private javax.swing.JLabel cardTwoNameLabel;
    private javax.swing.JLabel cardTwoNameText;
    private javax.swing.JLayeredPane cardTwoPane;
    private javax.swing.JLabel cardTwoType;
    private javax.swing.JButton exitButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton myCardsButton;
    private javax.swing.JButton myProfileButton;
    private javax.swing.JButton removeCardButton;
    private javax.swing.JButton updateBalanceButton;
    // End of variables declaration//GEN-END:variables

}
