/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.github.hasat.frame;

import io.github.hasat.database.MySQL;
import io.github.hasat.user.User;
import io.github.hasat.user.UserManager;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author hakan
 */
public class ChangePasswordFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFrame
     */
    public ChangePasswordFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        secondNewPasswordLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        backButton = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        changePasswordButton = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        currentPasswordLabel = new javax.swing.JLabel();
        newPasswordLabel = new javax.swing.JLabel();
        secondNewPasswordText = new javax.swing.JPasswordField();
        currentPasswordText = new javax.swing.JPasswordField();
        newPasswordText = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HASAT Ulaşım");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/bus.png")).getImage());
        setResizable(false);

        panel.setBackground(new java.awt.Color(2, 44, 74));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/newbus.png"))); // NOI18N
        logoLabel.setText("HASAT Ulaşım");
        logoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        secondNewPasswordLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        secondNewPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        secondNewPasswordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/password.png"))); // NOI18N
        secondNewPasswordLabel.setText("Yeni E-Posta Doğrula:");
        panel.add(secondNewPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));
        panel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 430, 11));
        panel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 430, 10));

        backButton.setBackground(new java.awt.Color(2, 44, 74));
        backButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/back.png"))); // NOI18N
        backButton.setText("Geri Dön");
        backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        backButton.setFocusPainted(false);
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backButtonMouseEntered(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        panel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 200, 80));

        warningLabel.setBackground(new java.awt.Color(2, 44, 74));
        warningLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(255, 255, 255));
        warningLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        warningLabel.setOpaque(true);
        panel.add(warningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 200, 170));

        changePasswordButton.setBackground(new java.awt.Color(2, 44, 74));
        changePasswordButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        changePasswordButton.setForeground(new java.awt.Color(255, 255, 255));
        changePasswordButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/change.png"))); // NOI18N
        changePasswordButton.setText("Şifre Değiştir");
        changePasswordButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        changePasswordButton.setFocusPainted(false);
        changePasswordButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changePasswordButtonMouseEntered(evt);
            }
        });
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });
        panel.add(changePasswordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 430, 80));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 10, 470));

        currentPasswordLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        currentPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        currentPasswordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/password.png"))); // NOI18N
        currentPasswordLabel.setText("Mevcut Şifre:");
        panel.add(currentPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        newPasswordLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        newPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        newPasswordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/password.png"))); // NOI18N
        newPasswordLabel.setText("Yeni Şifre:");
        panel.add(newPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        secondNewPasswordText.setBackground(new java.awt.Color(2, 44, 74));
        secondNewPasswordText.setForeground(new java.awt.Color(255, 255, 255));
        secondNewPasswordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        secondNewPasswordText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                secondNewPasswordTextKeyTyped(evt);
            }
        });
        panel.add(secondNewPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 430, 38));

        currentPasswordText.setBackground(new java.awt.Color(2, 44, 74));
        currentPasswordText.setForeground(new java.awt.Color(255, 255, 255));
        currentPasswordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        currentPasswordText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                currentPasswordTextKeyTyped(evt);
            }
        });
        panel.add(currentPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 430, 38));

        newPasswordText.setBackground(new java.awt.Color(2, 44, 74));
        newPasswordText.setForeground(new java.awt.Color(255, 255, 255));
        newPasswordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        newPasswordText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newPasswordTextKeyTyped(evt);
            }
        });
        panel.add(newPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 430, 38));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        
        new ProfileFrame().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        String password = String.valueOf(currentPasswordText.getPassword());
        String newPassword = String.valueOf(newPasswordText.getPassword());
        String newPassword2 = String.valueOf(secondNewPasswordText.getPassword());
        
        if (password.isEmpty()) {
            currentPasswordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Mevcut Şifre kısmını<br>&nbsp;doldurmalısınız!</html>");
            return;
        }
        
        if (password.length() < 4) {
            currentPasswordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Geçerli bir şifre<br>&nbsp;girmelisiniz!</html>");
            return;
        }
        
        if (newPassword.isEmpty()) {
            newPasswordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Yeni Şifre kısmını<br>&nbsp;doldurmalısınız!</html>");
            return;
        }
        
        if (newPassword.length() < 4) {
            newPasswordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Geçerli bir yeni Şifre<br>&nbsp;girmelisiniz!</html>");
            return;
        }
        
        if (newPassword2.isEmpty()) {
            secondNewPasswordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Yeni Şifre kısmını<br>&nbsp;doldurmalısınız!</html>");
            return;
        }
        
        if (newPassword2.length() < 4) {
            secondNewPasswordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Geçerli bir yeni Şifre<br>&nbsp;girmelisiniz!</html>");
            return;
        }
        
        if (!newPassword.equals(newPassword2)) {
            newPasswordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            secondNewPasswordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Yeni Şifre'ler<br>&nbsp;eşleşmiyor!</html>");
            return;
        }
       
        User user = UserManager.getUser();
        
        if (user == null) {
            dispose();
            
            new LoginFrame().setVisible(true);
            
            return;
        }
        
        if (!user.getPassword().equals(password)) {
            currentPasswordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Mevcut Şifreniz<br>&nbsp;yanlış!</html>");
            return;
        }
        
        MySQL.changePassword(user.getMail(), newPassword);
        
        user.setPassword(newPassword);
        
        warningLabel.setBackground(new Color(1,95,24));
        warningLabel.setText("<html>&nbsp;● Şifreniz başarıyla<br>&nbsp;değiştirildi!<br><br>&nbsp;Yönlendiriliyorsunuz...</html>");
        
        ActionListener action = (ActionEvent ae) -> {
            dispose();

            new ProfileFrame().setVisible(true);
        };

        Timer t = new Timer(3000, action);

        t.setRepeats(false);
        t.start();
    }//GEN-LAST:event_changePasswordButtonActionPerformed

    private void backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseEntered
        backButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_backButtonMouseEntered

    private void changePasswordButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordButtonMouseEntered
        changePasswordButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_changePasswordButtonMouseEntered

    private void secondNewPasswordTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secondNewPasswordTextKeyTyped
        if (String.valueOf(secondNewPasswordText.getPassword()).length() > 30) {
            evt.consume();
            return;
        }
        
        secondNewPasswordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_secondNewPasswordTextKeyTyped

    private void currentPasswordTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currentPasswordTextKeyTyped
        if (String.valueOf(currentPasswordText.getPassword()).length() > 30) {
            evt.consume();
            return;
        }
        
        currentPasswordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_currentPasswordTextKeyTyped

    private void newPasswordTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPasswordTextKeyTyped
        if (String.valueOf(newPasswordText.getPassword()).length() > 30) {
            evt.consume();
            return;
        }
        
        newPasswordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_newPasswordTextKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JLabel currentPasswordLabel;
    private javax.swing.JPasswordField currentPasswordText;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JPasswordField newPasswordText;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel secondNewPasswordLabel;
    private javax.swing.JPasswordField secondNewPasswordText;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
