/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.github.hasat.frame;

import io.github.hasat.database.MySQL;
import io.github.hasat.user.User;
import io.github.hasat.user.UserManager;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author hakan
 */
public class ChangePhoneFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFrame
     */
    public ChangePhoneFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        secondNewPhoneLabel = new javax.swing.JLabel();
        currentPhoneText = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        newSecondPhoneText = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        changePhoneButton = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        currentPhoneLabel = new javax.swing.JLabel();
        newPhoneLabel = new javax.swing.JLabel();
        newPhoneText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HASAT Ulaşım");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/bus.png")).getImage());
        setResizable(false);

        panel.setBackground(new java.awt.Color(2, 44, 74));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/newbus.png"))); // NOI18N
        logoLabel.setText("HASAT Ulaşım");
        logoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        secondNewPhoneLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        secondNewPhoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        secondNewPhoneLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/phone.png"))); // NOI18N
        secondNewPhoneLabel.setText("Yeni Telefon Numarası Doğrula:");
        panel.add(secondNewPhoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        currentPhoneText.setBackground(new java.awt.Color(2, 44, 74));
        currentPhoneText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        currentPhoneText.setForeground(new java.awt.Color(255, 255, 255));
        currentPhoneText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        currentPhoneText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                currentPhoneTextKeyTyped(evt);
            }
        });
        panel.add(currentPhoneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 430, 38));
        panel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 430, 11));
        panel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 430, 10));

        newSecondPhoneText.setBackground(new java.awt.Color(2, 44, 74));
        newSecondPhoneText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        newSecondPhoneText.setForeground(new java.awt.Color(255, 255, 255));
        newSecondPhoneText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        newSecondPhoneText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newSecondPhoneTextKeyTyped(evt);
            }
        });
        panel.add(newSecondPhoneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 430, 38));

        backButton.setBackground(new java.awt.Color(2, 44, 74));
        backButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/back.png"))); // NOI18N
        backButton.setText("Geri Dön");
        backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        backButton.setFocusPainted(false);
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backButtonMouseEntered(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        panel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 200, 80));

        warningLabel.setBackground(new java.awt.Color(2, 44, 74));
        warningLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(255, 255, 255));
        warningLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        warningLabel.setOpaque(true);
        panel.add(warningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 196, 200, 170));

        changePhoneButton.setBackground(new java.awt.Color(2, 44, 74));
        changePhoneButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        changePhoneButton.setForeground(new java.awt.Color(255, 255, 255));
        changePhoneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/change.png"))); // NOI18N
        changePhoneButton.setText("Telefon Numarası Değiştir");
        changePhoneButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        changePhoneButton.setFocusPainted(false);
        changePhoneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changePhoneButtonMouseEntered(evt);
            }
        });
        changePhoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePhoneButtonActionPerformed(evt);
            }
        });
        panel.add(changePhoneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 430, 80));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 10, 470));

        currentPhoneLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        currentPhoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        currentPhoneLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/phone.png"))); // NOI18N
        currentPhoneLabel.setText("Mevcut Telefon Numarası:");
        panel.add(currentPhoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        newPhoneLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        newPhoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        newPhoneLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/phone.png"))); // NOI18N
        newPhoneLabel.setText("Yeni Telefon Numarası:");
        panel.add(newPhoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        newPhoneText.setBackground(new java.awt.Color(2, 44, 74));
        newPhoneText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        newPhoneText.setForeground(new java.awt.Color(255, 255, 255));
        newPhoneText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        newPhoneText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newPhoneTextKeyTyped(evt);
            }
        });
        panel.add(newPhoneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 430, 38));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        
        new ProfileFrame().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void changePhoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePhoneButtonActionPerformed
        String phone = currentPhoneText.getText();
        String newPhone = newPhoneText.getText();
        String newPhone2 = newSecondPhoneText.getText();
        
        if (phone.isEmpty()) {
            currentPhoneText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Mevcut Telefon kısmını<br>&nbsp;doldurmalısınız!</html>");
            return;
        }
        
        if (phone.length() != 10) {
            currentPhoneText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Geçerli bir Telefon<br>&nbsp;girmelisiniz!</html>");
            return;
        }
        
        if (newPhone.isEmpty()) {
            newPhoneText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Yeni Telefon kısmını<br>&nbsp;doldurmalısınız!</html>");
            return;
        }
        
        if (newPhone.length() != 10) {
            newPhoneText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Geçerli bir yeni Telefon<br>&nbsp;girmelisiniz!</html>");
            return;
        }
        
        if (newPhone2.isEmpty()) {
            newSecondPhoneText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Yeni Telefon kısmını<br>&nbsp;doldurmalısınız!</html>");
            return;
        }
        
        if (newPhone2.length() != 10) {
            newPhoneText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Geçerli bir yeni Yelefon<br>&nbsp;girmelisiniz!</html>");
            return;
        }
        
        if (!newPhone.equals(newPhone2)) {
            newPhoneText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            newSecondPhoneText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Yeni Telefon'lar<br>&nbsp;eşleşmiyor!</html>");
            return;
        }
       
        User user = UserManager.getUser();
        
        if (user == null) {
            dispose();
            
            new LoginFrame().setVisible(true);
            
            return;
        }
        
        if (!user.getPhone().equals(phone)) {
            currentPhoneText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Mevcut Telefonunuz<br>&nbsp;yanlış!</html>");
            return;
        }
        
        MySQL.changePhone(user.getMail(), newPhone);
        
        user.setPhone(newPhone);
        
        warningLabel.setBackground(new Color(1,95,24));
        warningLabel.setText("<html>&nbsp;● Telefon numaranız<br>&nbsp;başarıyla değiştirildi!<br><br>&nbsp;&nbsp;Yönlendiriliyorsunuz...</html>");
        
        ActionListener action = (ActionEvent ae) -> {
            dispose();

            new ProfileFrame().setVisible(true);
        };

        Timer t = new Timer(3000, action);

        t.setRepeats(false);
        t.start();
    }//GEN-LAST:event_changePhoneButtonActionPerformed

    private void backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseEntered
        backButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_backButtonMouseEntered

    private void changePhoneButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePhoneButtonMouseEntered
        changePhoneButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_changePhoneButtonMouseEntered

    private void currentPhoneTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currentPhoneTextKeyTyped
        String key = String.valueOf(evt.getKeyChar());
        
        try {
            Integer.parseInt(key);
        } catch (NumberFormatException e) {
            evt.consume();
            return;
        }
        
        if (currentPhoneText.getText().length() > 9) {
            evt.consume();
            return;
        }
                
        currentPhoneText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_currentPhoneTextKeyTyped

    private void newPhoneTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPhoneTextKeyTyped
        String key = String.valueOf(evt.getKeyChar());
        
        try {
            Integer.parseInt(key);
        } catch (NumberFormatException e) {
            evt.consume();
            return;
        }
        
        if (newPhoneText.getText().length() > 9) {
            evt.consume();
            return;
        }
                
        newPhoneText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_newPhoneTextKeyTyped

    private void newSecondPhoneTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newSecondPhoneTextKeyTyped
       String key = String.valueOf(evt.getKeyChar());
        
        try {
            Integer.parseInt(key);
        } catch (NumberFormatException e) {
            evt.consume();
            return;
        }
        
        if (newSecondPhoneText.getText().length() > 9) {
            evt.consume();
            return;
        }
                
        newSecondPhoneText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_newSecondPhoneTextKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton changePhoneButton;
    private javax.swing.JLabel currentPhoneLabel;
    private javax.swing.JTextField currentPhoneText;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel newPhoneLabel;
    private javax.swing.JTextField newPhoneText;
    private javax.swing.JTextField newSecondPhoneText;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel secondNewPhoneLabel;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
