/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.github.hasat.frame;

import io.github.hasat.database.MySQL;
import io.github.hasat.user.User;
import io.github.hasat.user.UserManager;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author hakan
 */
public class ChangeMailFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFrame
     */
    public ChangeMailFrame() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        secondNewMailLabel = new javax.swing.JLabel();
        currentMailText = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        secondNewMailText = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        changeMailButton = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        currentMailLabel = new javax.swing.JLabel();
        newMailLabel = new javax.swing.JLabel();
        newLabelText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HASAT Ulaşım");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/bus.png")).getImage());
        setResizable(false);

        panel.setBackground(new java.awt.Color(2, 44, 74));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/newbus.png"))); // NOI18N
        logoLabel.setText("HASAT Ulaşım");
        logoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        secondNewMailLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        secondNewMailLabel.setForeground(new java.awt.Color(255, 255, 255));
        secondNewMailLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/mail.png"))); // NOI18N
        secondNewMailLabel.setText("Yeni E-Posta Doğrula:");
        panel.add(secondNewMailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        currentMailText.setBackground(new java.awt.Color(2, 44, 74));
        currentMailText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        currentMailText.setForeground(new java.awt.Color(255, 255, 255));
        currentMailText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        currentMailText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                currentMailTextKeyTyped(evt);
            }
        });
        panel.add(currentMailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 430, 38));
        panel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 430, 11));
        panel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 430, 10));

        secondNewMailText.setBackground(new java.awt.Color(2, 44, 74));
        secondNewMailText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        secondNewMailText.setForeground(new java.awt.Color(255, 255, 255));
        secondNewMailText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        secondNewMailText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                secondNewMailTextKeyTyped(evt);
            }
        });
        panel.add(secondNewMailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 430, 38));

        backButton.setBackground(new java.awt.Color(2, 44, 74));
        backButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/back.png"))); // NOI18N
        backButton.setText("Geri Dön");
        backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        backButton.setFocusPainted(false);
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backButtonMouseEntered(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        panel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 200, 80));

        warningLabel.setBackground(new java.awt.Color(2, 44, 74));
        warningLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(255, 255, 255));
        warningLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        warningLabel.setOpaque(true);
        panel.add(warningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 196, 200, 170));

        changeMailButton.setBackground(new java.awt.Color(2, 44, 74));
        changeMailButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        changeMailButton.setForeground(new java.awt.Color(255, 255, 255));
        changeMailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/change.png"))); // NOI18N
        changeMailButton.setText("E-Posta Değiştir");
        changeMailButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        changeMailButton.setFocusPainted(false);
        changeMailButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changeMailButtonMouseEntered(evt);
            }
        });
        changeMailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeMailButtonActionPerformed(evt);
            }
        });
        panel.add(changeMailButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 430, 80));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 10, 470));

        currentMailLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        currentMailLabel.setForeground(new java.awt.Color(255, 255, 255));
        currentMailLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/mail.png"))); // NOI18N
        currentMailLabel.setText("Mevcut E-Posta:");
        panel.add(currentMailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        newMailLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        newMailLabel.setForeground(new java.awt.Color(255, 255, 255));
        newMailLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/mail.png"))); // NOI18N
        newMailLabel.setText("Yeni E-Posta:");
        panel.add(newMailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        newLabelText.setBackground(new java.awt.Color(2, 44, 74));
        newLabelText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        newLabelText.setForeground(new java.awt.Color(255, 255, 255));
        newLabelText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        newLabelText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newLabelTextKeyTyped(evt);
            }
        });
        panel.add(newLabelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 430, 38));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        
        new ProfileFrame().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void changeMailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeMailButtonActionPerformed
        String mail = currentMailText.getText();
        String newMail = newLabelText.getText();
        String newMail2 = secondNewMailText.getText();
        
        if (mail.isEmpty()) {
            currentMailText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Mevcut E-Posta kısmını<br>&nbsp;doldurmalısınız!</html>");
            return;
        }
        
        if (!mail.contains("@") || mail.length() < 5) {
            currentMailText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Geçerli bir E-Posta<br>&nbsp;girmelisiniz!</html>");
            return;
        }
        
        if (newMail.isEmpty()) {
            newLabelText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Yeni E-Posta kısmını<br>&nbsp;doldurmalısınız!</html>");
            return;
        }
        
        if (!newMail.contains("@") || newMail.length() < 5) {
            newLabelText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Geçerli bir yeni E-Posta<br>&nbsp;girmelisiniz!</html>");
            return;
        }
        
        if (newMail2.isEmpty()) {
            secondNewMailText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Yeni E-Posta kısmını<br>&nbsp;doldurmalısınız!</html>");
            return;
        }
        
        if (!newMail2.contains("@") || newMail2.length() < 5) {
            newLabelText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Geçerli bir yeni E-Posta<br>&nbsp;girmelisiniz!</html>");
            return;
        }
        
        if (!newMail.equals(newMail2)) {
            newLabelText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            secondNewMailText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Yeni E-Posta'lar<br>&nbsp;eşleşmiyor!</html>");
            return;
        }
       
        User user = UserManager.getUser();
        
        if (user == null) {
            dispose();
            
            new LoginFrame().setVisible(true);
            
            return;
        }
        
        if (!user.getMail().equals(mail)) {
            currentMailText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            warningLabel.setBackground(new Color(99,16,1));
            warningLabel.setText("<html>&nbsp;● Mevcut E-Postanız<br>&nbsp;yanlış!</html>");
            return;
        }
        
        MySQL.changeMail(mail, newMail);
        
        user.setMail(newMail);
        
        warningLabel.setBackground(new Color(1,95,24));
        warningLabel.setText("<html>&nbsp;● E-Postanız başarıyla<br>&nbsp;değiştirildi!<br><br>&nbsp;Yönlendiriliyorsunuz...</html>");
        
        ActionListener action = (ActionEvent ae) -> {
            dispose();

            new ProfileFrame().setVisible(true);
        };

        Timer t = new Timer(3000, action);

        t.setRepeats(false);
        t.start();
    }//GEN-LAST:event_changeMailButtonActionPerformed

    private void backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseEntered
        backButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_backButtonMouseEntered

    private void changeMailButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeMailButtonMouseEntered
        changeMailButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_changeMailButtonMouseEntered

    private void currentMailTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currentMailTextKeyTyped
        if (currentMailText.getText().length() > 30) {
            evt.consume();
            return;
        }
                
        currentMailText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_currentMailTextKeyTyped

    private void newLabelTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newLabelTextKeyTyped
        if (newLabelText.getText().length() > 30) {
            evt.consume();
            return;
        }
                
        newLabelText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_newLabelTextKeyTyped

    private void secondNewMailTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secondNewMailTextKeyTyped
        if (secondNewMailText.getText().length() > 30) {
            evt.consume();
            return;
        }
                
        secondNewMailText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_secondNewMailTextKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton changeMailButton;
    private javax.swing.JLabel currentMailLabel;
    private javax.swing.JTextField currentMailText;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JTextField newLabelText;
    private javax.swing.JLabel newMailLabel;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel secondNewMailLabel;
    private javax.swing.JTextField secondNewMailText;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
