/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package io.github.hasat.frame;

import io.github.hasat.card.Card;
import io.github.hasat.database.MySQL;
import io.github.hasat.user.User;
import io.github.hasat.user.UserManager;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.Timer;

/**
 *
 * @author hakan
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        mailLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mailText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        passwordLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        exitButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HASAT Ulaşım");
        setBackground(new java.awt.Color(55, 38, 91));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/bus.png")).getImage());
        setResizable(false);

        panel.setBackground(new java.awt.Color(2, 44, 74));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/newbus.png"))); // NOI18N
        logoLabel.setText("  HASAT Ulaşım");
        logoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        logoLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 320, 130));

        mailLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        mailLabel.setForeground(new java.awt.Color(255, 255, 255));
        mailLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/login.png"))); // NOI18N
        mailLabel.setText("E-Posta:");
        panel.add(mailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel3.setBackground(new java.awt.Color(2, 44, 74));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setOpaque(true);
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 610, 50));

        mailText.setBackground(new java.awt.Color(2, 44, 74));
        mailText.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        mailText.setForeground(new java.awt.Color(255, 255, 255));
        mailText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        mailText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mailTextKeyTyped(evt);
            }
        });
        panel.add(mailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 500, 38));

        passwordText.setBackground(new java.awt.Color(2, 44, 74));
        passwordText.setForeground(new java.awt.Color(255, 255, 255));
        passwordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        passwordText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordTextKeyTyped(evt);
            }
        });
        panel.add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 500, 38));

        registerButton.setBackground(new java.awt.Color(2, 44, 74));
        registerButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/register.png"))); // NOI18N
        registerButton.setText("Kayıt Ol");
        registerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        registerButton.setFocusPainted(false);
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerButtonMouseEntered(evt);
            }
        });
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        panel.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 220, 60));

        loginButton.setBackground(new java.awt.Color(2, 44, 74));
        loginButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/login.png"))); // NOI18N
        loginButton.setText("Giriş Yap");
        loginButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        loginButton.setFocusPainted(false);
        loginButton.setPreferredSize(new java.awt.Dimension(96, 32));
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginButtonMouseEntered(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        panel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 220, 60));

        passwordLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/password.png"))); // NOI18N
        passwordLabel.setText("Şifre:");
        panel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 96, -1));
        panel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 610, 8));

        exitButton1.setBackground(new java.awt.Color(2, 44, 74));
        exitButton1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        exitButton1.setForeground(new java.awt.Color(250, 49, 74));
        exitButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/logout.png"))); // NOI18N
        exitButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 49, 74), 1, true));
        exitButton1.setFocusPainted(false);
        exitButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButton1MouseEntered(evt);
            }
        });
        exitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton1ActionPerformed(evt);
            }
        });
        panel.add(exitButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        this.dispose();
        
        new RegisterFrame().setVisible(true);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String mail = mailText.getText();
        
        if (mail.isEmpty()) {
            mailText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            jLabel3.setBackground(new Color(99,16,1));
            jLabel3.setText("   ● E-Posta kısmını doldurmalısınız!");
            return;
        }
        
        if (!mail.contains("@") || mail.length() < 5) {
            mailText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            jLabel3.setBackground(new Color(99,16,1));
            jLabel3.setText("   ● Geçerli bir E-Posta girmelisiniz!");
            return;
        }
        
        String password = String.valueOf(passwordText.getPassword());
        
        if (password.isEmpty()) {
            passwordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            jLabel3.setBackground(new Color(99,16,1));
            jLabel3.setText("   ● Şifre kısmını doldurmalısınız!");
            return;
        }
        
        if (password.length() < 4) {
            passwordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            jLabel3.setBackground(new Color(99,16,1));
            jLabel3.setText("   ● Geçerli bir şifre girmelisiniz!");
            return;
        }
        
        if (!MySQL.isUserExists(mail)) {
            jLabel3.setBackground(new Color(99,16,1));
            jLabel3.setText("   ● Hesabınız bulunamadı!");
            return;
        }
        
        String accountPassword = MySQL.getPasswordOfMail(mail);
        
        if (accountPassword.equals("null") || !accountPassword.equals(password)) {
            mailText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            passwordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 49, 74)));
            jLabel3.setBackground(new Color(99,16,1));
            jLabel3.setText("   ● Yanlış E-Posta veya şifre girdiniz!");
            return;
        }
        
        User user = MySQL.getUserFromMail(mail);
        
        if (user == null) {
            jLabel3.setBackground(new Color(99,16,1));
            jLabel3.setText("   ● Hesabınız bulunamadı!");
            return;
        }
        
        List<Card> cards = MySQL.getUserCards(user.getID());
        
        user.setCards(cards);
        
        UserManager.setUser(user);
                            
        jLabel3.setBackground(new Color(1,95,24));
        jLabel3.setText("   ● Giriş başarılı!");

        ActionListener action = (ActionEvent ae) -> {
            dispose();

            new ProfileFrame().setVisible(true);
        };

        Timer t = new Timer(3000, action);

        t.setRepeats(false);
        t.start();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void mailTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailTextKeyTyped
        if (mailText.getText().length() > 30) {
            evt.consume();
            return;
        }
        
        mailText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_mailTextKeyTyped

    private void passwordTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTextKeyTyped
        if (String.valueOf(passwordText.getPassword()).length() > 30) {
            evt.consume();
            return;
        }
        
        passwordText.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_passwordTextKeyTyped

    private void loginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseEntered
        loginButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_loginButtonMouseEntered

    private void registerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseEntered
        registerButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_registerButtonMouseEntered

    private void exitButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButton1MouseEntered
        registerButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_exitButton1MouseEntered

    private void exitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_exitButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JTextField mailText;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables
}
