/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package io.github.hasat.frame;

import io.github.hasat.user.User;
import io.github.hasat.user.UserManager;
import java.awt.Cursor;

/**
 *
 * @author hakan
 */
public class ProfileFrame extends javax.swing.JFrame {

    /** Creates new form ProfilePage */
    public ProfileFrame() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        if (UserManager.isUserExists()) {
            User user = UserManager.getUser();
            
            nameLabel.setText(nameLabel.getText()
                    .replace("<name>", user.getName())
                    .replace("<surname>", user.getSurname()));
            
            idLabelValue.setText(idLabelValue.getText().replace("<id>", user.getID() + ""));
            
            mailLabelValue.setText(mailLabelValue.getText().replace("<mail>", user.getMail()));
            
            registerLabelValue.setText(registerLabelValue.getText().replace("<registerTime>", user.getRegisterTime()));
            
            phoneLabelValue.setText(phoneLabelValue.getText().replace("<phone>", user.getPhone()));
        } else {
            dispose();
            
            new LoginFrame().setVisible(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        exitButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        registerLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        phoneLabelValue = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        mailLabel = new javax.swing.JLabel();
        profileButton = new javax.swing.JButton();
        helloLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        idLabelValue = new javax.swing.JLabel();
        mailLabelValue = new javax.swing.JLabel();
        registerLabelValue = new javax.swing.JLabel();
        passwordChangeButton = new javax.swing.JButton();
        mailChangeButton = new javax.swing.JButton();
        phoneChangeButton = new javax.swing.JButton();
        myCardsButton = new javax.swing.JButton();
        addCardButton = new javax.swing.JButton();
        removeCardButton = new javax.swing.JButton();
        updateBalanceButton = new javax.swing.JButton();
        busTimesButton = new javax.swing.JButton();
        cardSettingsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HASAT Ulaşım");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/bus.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(2, 44, 74));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 20)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/bus16px.png"))); // NOI18N
        logoLabel.setText("  HASAT Ulaşım");
        logoLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        logoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        logoLabel.setIconTextGap(1);
        logoLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 70));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 10, 530));

        exitButton.setBackground(new java.awt.Color(2, 44, 74));
        exitButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(250, 49, 74));
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/logout.png"))); // NOI18N
        exitButton.setText("Çıkış Yap");
        exitButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 49, 74), 1, true));
        exitButton.setFocusPainted(false);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 210, 40));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 210, 10));

        registerLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(255, 255, 255));
        registerLabel.setText("● Kayıt Zamanı:");
        jPanel1.add(registerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 120, 40));

        nameLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("<name> <surname>");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 390, 50));

        phoneLabelValue.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        phoneLabelValue.setForeground(new java.awt.Color(255, 255, 255));
        phoneLabelValue.setText("<phone>");
        jPanel1.add(phoneLabelValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 280, 40));

        phoneLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneLabel.setText("● Telefon Numarası:");
        jPanel1.add(phoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 160, 40));

        mailLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        mailLabel.setForeground(new java.awt.Color(255, 255, 255));
        mailLabel.setText("● E-Posta:");
        jPanel1.add(mailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 80, 40));

        profileButton.setBackground(new java.awt.Color(2, 44, 74));
        profileButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        profileButton.setForeground(new java.awt.Color(255, 255, 255));
        profileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/name.png"))); // NOI18N
        profileButton.setText("Profilim");
        profileButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        profileButton.setFocusPainted(false);
        profileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileButtonMouseEntered(evt);
            }
        });
        jPanel1.add(profileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 210, 40));

        helloLabel.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        helloLabel.setForeground(new java.awt.Color(255, 255, 255));
        helloLabel.setText("Merhaba,");
        jPanel1.add(helloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 120, -1));

        idLabel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        idLabel.setForeground(new java.awt.Color(255, 255, 255));
        idLabel.setText("● Numara:");
        jPanel1.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 90, 40));

        idLabelValue.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        idLabelValue.setForeground(new java.awt.Color(255, 255, 255));
        idLabelValue.setText("<id>");
        jPanel1.add(idLabelValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 420, 40));

        mailLabelValue.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        mailLabelValue.setForeground(new java.awt.Color(255, 255, 255));
        mailLabelValue.setText("<mail>");
        jPanel1.add(mailLabelValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 420, 40));

        registerLabelValue.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        registerLabelValue.setForeground(new java.awt.Color(255, 255, 255));
        registerLabelValue.setText("<registerTime>");
        jPanel1.add(registerLabelValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 380, 40));

        passwordChangeButton.setBackground(new java.awt.Color(2, 44, 74));
        passwordChangeButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        passwordChangeButton.setForeground(new java.awt.Color(255, 255, 255));
        passwordChangeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/password.png"))); // NOI18N
        passwordChangeButton.setText("<html>&nbsp;&nbsp;Şifre<br>Değiştir</html>");
        passwordChangeButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        passwordChangeButton.setFocusPainted(false);
        passwordChangeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        passwordChangeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        passwordChangeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordChangeButtonMouseEntered(evt);
            }
        });
        passwordChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordChangeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(passwordChangeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 160, 110));

        mailChangeButton.setBackground(new java.awt.Color(2, 44, 74));
        mailChangeButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        mailChangeButton.setForeground(new java.awt.Color(255, 255, 255));
        mailChangeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/mail.png"))); // NOI18N
        mailChangeButton.setText("<html>E-Posta<br>Değiştir</html>");
        mailChangeButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        mailChangeButton.setFocusPainted(false);
        mailChangeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mailChangeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mailChangeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mailChangeButtonMouseEntered(evt);
            }
        });
        mailChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailChangeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(mailChangeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 160, 110));

        phoneChangeButton.setBackground(new java.awt.Color(2, 44, 74));
        phoneChangeButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        phoneChangeButton.setForeground(new java.awt.Color(255, 255, 255));
        phoneChangeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/phone.png"))); // NOI18N
        phoneChangeButton.setText("<html>Telefon Numarası<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Değiştir</html>");
        phoneChangeButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        phoneChangeButton.setFocusPainted(false);
        phoneChangeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        phoneChangeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        phoneChangeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                phoneChangeButtonMouseEntered(evt);
            }
        });
        phoneChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneChangeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(phoneChangeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 170, 110));

        myCardsButton.setBackground(new java.awt.Color(2, 44, 74));
        myCardsButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        myCardsButton.setForeground(new java.awt.Color(255, 255, 255));
        myCardsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/card.png"))); // NOI18N
        myCardsButton.setText("Kartlarım");
        myCardsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        myCardsButton.setFocusPainted(false);
        myCardsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myCardsButtonMouseEntered(evt);
            }
        });
        myCardsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myCardsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(myCardsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 210, 40));

        addCardButton.setBackground(new java.awt.Color(2, 44, 74));
        addCardButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        addCardButton.setForeground(new java.awt.Color(255, 255, 255));
        addCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/add.png"))); // NOI18N
        addCardButton.setText("Kart Ekle");
        addCardButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        addCardButton.setFocusPainted(false);
        addCardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addCardButtonMouseEntered(evt);
            }
        });
        addCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCardButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addCardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 210, 40));

        removeCardButton.setBackground(new java.awt.Color(2, 44, 74));
        removeCardButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        removeCardButton.setForeground(new java.awt.Color(255, 255, 255));
        removeCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/remove.png"))); // NOI18N
        removeCardButton.setText("Kart Sil");
        removeCardButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        removeCardButton.setFocusPainted(false);
        removeCardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeCardButtonMouseEntered(evt);
            }
        });
        removeCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCardButtonActionPerformed(evt);
            }
        });
        jPanel1.add(removeCardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 210, 40));

        updateBalanceButton.setBackground(new java.awt.Color(2, 44, 74));
        updateBalanceButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        updateBalanceButton.setForeground(new java.awt.Color(255, 255, 255));
        updateBalanceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/money.png"))); // NOI18N
        updateBalanceButton.setText("Bakiye Yükle");
        updateBalanceButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        updateBalanceButton.setFocusPainted(false);
        updateBalanceButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBalanceButtonMouseEntered(evt);
            }
        });
        updateBalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBalanceButtonActionPerformed(evt);
            }
        });
        jPanel1.add(updateBalanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 210, 40));

        busTimesButton.setBackground(new java.awt.Color(2, 44, 74));
        busTimesButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        busTimesButton.setForeground(new java.awt.Color(255, 255, 255));
        busTimesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/clock.png"))); // NOI18N
        busTimesButton.setText("Otobüs Saatleri");
        busTimesButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        busTimesButton.setFocusPainted(false);
        busTimesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                busTimesButtonMouseEntered(evt);
            }
        });
        busTimesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busTimesButtonActionPerformed(evt);
            }
        });
        jPanel1.add(busTimesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 210, 40));

        cardSettingsButton.setBackground(new java.awt.Color(2, 44, 74));
        cardSettingsButton.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        cardSettingsButton.setForeground(new java.awt.Color(255, 255, 255));
        cardSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/io/github/hasat/images/settings.png"))); // NOI18N
        cardSettingsButton.setText("Kart Ayarları");
        cardSettingsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        cardSettingsButton.setFocusPainted(false);
        cardSettingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cardSettingsButtonMouseEntered(evt);
            }
        });
        cardSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardSettingsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cardSettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void passwordChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordChangeButtonActionPerformed
        dispose();
        
        new ChangePasswordFrame().setVisible(true);
    }//GEN-LAST:event_passwordChangeButtonActionPerformed

    private void mailChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailChangeButtonActionPerformed
        dispose();
        
        new ChangeMailFrame().setVisible(true);
    }//GEN-LAST:event_mailChangeButtonActionPerformed

    private void phoneChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneChangeButtonActionPerformed
        dispose();
        
        new ChangePhoneFrame().setVisible(true);
    }//GEN-LAST:event_phoneChangeButtonActionPerformed

    private void profileButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileButtonMouseEntered
        profileButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_profileButtonMouseEntered

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        exitButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_exitButtonMouseEntered

    private void mailChangeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailChangeButtonMouseEntered
        mailChangeButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_mailChangeButtonMouseEntered

    private void phoneChangeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneChangeButtonMouseEntered
        phoneChangeButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_phoneChangeButtonMouseEntered

    private void passwordChangeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordChangeButtonMouseEntered
        passwordChangeButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_passwordChangeButtonMouseEntered

    private void myCardsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myCardsButtonMouseEntered
        myCardsButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_myCardsButtonMouseEntered

    private void myCardsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myCardsButtonActionPerformed
        dispose();

        new CardsFrame().setVisible(true);
    }//GEN-LAST:event_myCardsButtonActionPerformed

    private void addCardButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCardButtonMouseEntered
        addCardButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_addCardButtonMouseEntered

    private void addCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCardButtonActionPerformed
        dispose();

        new AddCardFrame().setVisible(true);
    }//GEN-LAST:event_addCardButtonActionPerformed

    private void removeCardButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCardButtonMouseEntered
        removeCardButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_removeCardButtonMouseEntered

    private void removeCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCardButtonActionPerformed
        dispose();

        new RemoveCardFrame().setVisible(true);
    }//GEN-LAST:event_removeCardButtonActionPerformed

    private void updateBalanceButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBalanceButtonMouseEntered
        updateBalanceButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_updateBalanceButtonMouseEntered

    private void updateBalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBalanceButtonActionPerformed
        dispose();

        new BalanceCardFrame().setVisible(true);
    }//GEN-LAST:event_updateBalanceButtonActionPerformed

    private void busTimesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busTimesButtonMouseEntered
        busTimesButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_busTimesButtonMouseEntered

    private void busTimesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busTimesButtonActionPerformed
        dispose();
        
        new BusTimesFrame().setVisible(true);
    }//GEN-LAST:event_busTimesButtonActionPerformed

    private void cardSettingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardSettingsButtonMouseEntered
        cardSettingsButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_cardSettingsButtonMouseEntered

    private void cardSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardSettingsButtonActionPerformed
        dispose();
        
        new CardSettingsFrame().setVisible(true);
    }//GEN-LAST:event_cardSettingsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCardButton;
    private javax.swing.JButton busTimesButton;
    private javax.swing.JButton cardSettingsButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel helloLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idLabelValue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton mailChangeButton;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JLabel mailLabelValue;
    private javax.swing.JButton myCardsButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton passwordChangeButton;
    private javax.swing.JButton phoneChangeButton;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel phoneLabelValue;
    private javax.swing.JButton profileButton;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JLabel registerLabelValue;
    private javax.swing.JButton removeCardButton;
    private javax.swing.JButton updateBalanceButton;
    // End of variables declaration//GEN-END:variables

}
